[package]
name    = "{{ crate_name }}"
version = "0.1.0"
authors = ["{{ authors }}"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
panic-halt   = "0.2"
{% if mcu == "esp32c3" -%}
esp32c3-hal = { package = "esp32c3-hal", git = "https://github.com/esp-rs/esp-hal.git" }
riscv-rt = { version = "0.8", optional = true }
{%- else -%}
{{ mcu }}-hal = { package = "{{ mcu }}-hal", git = "https://github.com/esp-rs/esp-hal.git" }
xtensa-lx-rt = { version = "0.11.0", features = ["{{ mcu }}"], optional = true }
{%- endif %}

[features]
default = ["rt"]
{% if mcu == "esp32c3" -%}
rt = ["riscv-rt"]
{%- else -%}
rt = ["xtensa-lx-rt"]
{%- endif %}
